const Strings = {
  Score: "ანგარიშები",
  Current: "მიმდინარე",
  Favorites: "ფავორიტები",
  Hello: "გამარჯობა",
  Categories: "კატეგორიები",
  PopularLeagues: "პოპულარული ლიგები",
  PopularClubs: "პოპულარული კლუბები",
  news: "ახალი ამბები",
  Transfers: "ტრანსფერები",
  Scandals: "სკანდალები",
  Highlights: "ჰაილაითები",
  Stories: "ისტორიები",
  CommentsAlertText: "კომენტარის დასაწერად იუზერი უნდა იყოს სისტემაში",
  Meetings: "ურთიერთ შეხვედრები",
  Midfielder: "ნახევარმცველი",
  Attacker: "თავდამსხმელი",
  Guard: "მცველი",
  Rating: "რეიტინგი",
  PlayedTime: "ნათამაშები დრო",
  Goals: "გოლები",
  assists: "ასისტები",
  Fined: "დაჯარიმდა",
  FinedHim: "დაჯარიმდნენ მასზე",
  AttemptDribbling: " დრიბლინგის მცდელობა",
  SuccessfulDribbling: "წარმატებული დრიბლინგი",
  MissedDribbling: "დრიბლინგით გაცდნენ",
  Duel: "დუელი",
  WonDuel: "მოგებული დუელი",
  WonAirDuel: "მოგებული საჰაერო დუელი",
  Offside: "თამაშგარე",
  Deprivation: "ართმევა",
  block: "ბლოკი",
  Intercept: "ჩაჭრა",
  LostTheBall: "დაკარგა ბურთი",
  InitialComposition: "საწყისი შემადგენლობა",
  SpareChair: "სათადარიგო სკამი",
  SpreadsheetsAreNotnown: "ცხრილები ჯერ არ არის ცნობილი",
  Club: "კლუბი",
  PlayerRating: "მოთამაშეთა რეიტინგი",
  TotalShots: "სულ დარტყმები",
  FullName: "სრული სახელი",
  PlayerName: "ფეხბურთელის სახელი",
  Match: "მატჩი",
  Save: "სეივი",
  DryDoor: "მშრალი კარი",
  Assistant: "ასისტი",
  Goal: "გოლი",
  ChangePassword: "პაროლის შეცვლა",
  Remember: "დამახსოვრება",
  Messages: "შეტყობინებები",
  ReceiveMessages: "შეტყობინებების მიღება აპლიკაციიდან",
  LogOut: "ანგარიშიდან გამოსვლა",
  Subscribe: "გამოიწერეთ",
  Subscribed: "გამოწერილია",
  ChooseFavAthlete: "აირჩიეთ ფავორიტი სპორტსმენი",
  ChooseFavTeam: "აირჩიეთ ფავორიტი გუნდი",
  YouWillReceiveNews: "თქვენ მიიღებთ სიახლეებს, მომდევნო მატჩებზე ინფორმაციებს და ა.შ.",
  IncorrectData: "მონაცემები არასწორია",
  mailInUse: "მეილი გამოყენებულია",
  Reply: "გამოხმაურება",
  Comments: "კომენტარები",
  LastMatches: "ბოლო მატჩები:",
  ShowMoreMatches: "მეტი მატჩების ჩვენება",
  Close: "დახურვა",
  TotalDarts: "სულ დარტმები",
  BeatsOnThePole: "ძელზე გარტყმები",
  Pass: "პასი",
  AccuracyOfPasses: "პასების სიზუსტე",
  Shot: "ჩაწოდება",
  AccurateShooting: "ზუსტი ჩაწოდება",
  KeyPass: "საკვანძო პასი",
  AccuracyOfShots: "დარტყმების სიზუსტე",
  BehindTheDoor: "კარს მიღმა",
  directionDoor: "კარის მიმართულებით",
  PassStatistics: "პასების სტატისტიკა",
  MatchNotStarted: "მატჩი ჯერ არ დაწყებულა",
  SquadWillAppear: "შემადგენლობა გამოჩნდება მატჩის დაწყებამდე 1 საათით ადრე",
  FirstHalf: "პირველი ტაიმი",
  SecondHalf: "მეორე ტაიმი",
  ViewAllPlayers: "ყველა ფეხბურთელის ნახვა",
  ShowStatistics: "სტატისტიკის ჩვენება",
  SelectPlayers: "აირჩიეთ მოთამაშეები",
  TotalBlow: "სულ დარტყმა",
  AccurateShot: "ზუსტი დარტყმა",
  Minute: "წუთი",
  AccuratePass: "ზუსტი პასი",
  HitThePost: "გაარტყა ძელს",
  PlaceOfBirth: "დაბადების ადგილი",
  DateOfBirth: "დაბადების თარიღი",
  Height: "სიმაღლე",
  Weight: "წონა",
  Transfer: "გადაცემა",
  Card: "ბარათი",
  PremierLeague: "პრემიერ ლიგა",
  ViewAllMatches: "ყველა მატჩის ნახვა",
  NoNewsAvailable: "სიახლეები არ მოიპოვება",
  Cards: "ბარათები",
  Player: "მოთამაშე",
  TransferPrice: "ტრანსფერის ფასი",
  Tour: "ტური",
  Article: "სტატიაზე:",
  PasswordDoesNotMatch: "პაროლი არ ემთხვევა",
  EnterCurrentPassword: "მიუთითეთ მიმდინარე პაროლი",
  EnterNewPassword: "მიუთითეთ ახალი პაროლი",
  RepeatNewPassword: "გაიმეორეთ ახალი პაროლი",
  EnterLeagueName: "ჩაწერეთ ლიგის სახელი",
  SearchDesiredTeam: "მოძებნეთ სასურველი გუნდი",
  AddHighlights: "მონიშნულების დამატება",
  LeagueAverageStatistics: "ლიგის საშუალო სტატისტიკა",
  TeamsCount: "გუნდების რაოდენობა",
  MatchesCount: "მატჩების რაოდენობა",
  NumberMatchesPlayed: "ჩატატრებული მატჩების რაოდენობა",
  NumberOfGoals: "გოლების რაოდენობა",
  BothTeamsScored: "მატჩი რომელშიც ორივე გუნდმა გაიტანა",
  GoalMatch: "გოლი მატჩში საშ.",
  YellowCards: "ყვითელი ბარათები",
  RedCards: "წითელი ბარათები",
  YellowCardInMatch: "ყვითელი ბარათი მატჩში საშ.",
  RedCardInMatch: "წითელი ბარათი მატჩში საშ.",
  TeamMostGoals: "გუნდი ყველაზე მეტი გოლით",
  TeamMostMissedGoals: "გუნდი ყველაზე მეტი გაშვებული გოლით",
  ScorerOfSeason: "სეზონის ბომბარდირი",
  BestAssistantSeason: "სეზონის საუკეთესო ასისტენტი",
  MostDryDoors: "ყველაზე მეტი მშრალად შენახული კარი",
  GoalPassesEveryMinute: "გოლი გადის ყოველ წუთში",
  CornerMatc: "კუთხური მატჩში საშ.",
  MostCornerMatch: "ყველაზე მეტი კუთხური",
  GoalScoredHome: "სახლში გატანილი გოლი საშ.",
  AwayGoalScored: "სტუმრად გატანილი გოლი საშ.",
  AverageStatisticsNotObtained: "საშუალო სტატისტიკა არ მოიპოვება",
  StatisticsNotObtained: "სტატისტიკა არ მოიპოვება",
  Home: "სახლში",
  Guest: "სტუმრად",
  WonTotal: "მოგებული სულ",
  DrawTotal: "ფრე სულ",
  LossTotal: "წაგება სულ",
  TotalGoalsScored: "გატანილი გოლი სულ",
  MissedGoalTotal: "გაშვებული გოლი სულ",
  DryStoredDoor: "მშრალად შენახული კარი",
  GoalScoringPeriod: "გოლის გატანის პერიოდი",
  GoalPeriod: "გოლის გაშვების პერიოდი",
  GoalScoredMatch: "მატჩში გატანილი გოლი საშ.",
  GoalMissedInMatch: "მატჩში გაშვებული გოლი საშ.",
  FirstGoalAverage: "პირველი გატანილი გოლი საშ.",
  FirstMissedGoalGcored: "პირველი გაშვებული გოლი საშ.",
  Attack: "შეტევა",
  DangerousAttack: "სახიფათო შეტევა",
  PossessionOfBall: "ბურთის ფლობა საშ.",
  AccurateShotInMatch: "ზუსტი დარტყმა მატჩში საშ.",
  Fine: "ჯარიმა",
  PenaltyInMatch: "ჯარიმა მატჩში საშ.",
  AngularTotal: "კუთხური სულ",
  PlayerRatingAverage: "ფეხბურთელთა რეიტინგი საშ.",
  PlayerRatingInMatch: "ფეხბურთელთა რეიტინგი მატჩში საშ.",
  WriteComment: "დაწერეთ კომენტარი",
  Tags: "ტეგები",
  Video: "ვიდეო",
  SimilarNews: "მსგავსი სიახლეები",
  FindTagAndSubscribe: "მოძებნე ტეგი და გამოიწერე",
  Goalkeepers: "მეკარეები",
  Defenders: "მცველები",
  Midfielders: "ნახევარმცველები",
  Attackers: "თავდამსხმელები",
  TotalTimePlayed: "ნათამაშები ჯამური დრო",
  GoalsScored: "გატანილი გოლები",
  MatchHeld: "ჩატარებული მატჩი",
  InTheMain: "ძირითადში",
  OnSpare: "სათადარიგოზე",
  OwnGoal: "ავტოგოლი",
  BallWasTakenAway: "ბურთი აართვეს",
  PenaltyEarned: "მოპოვებული პენალტი",
  PenaltyTaken: "გატანილი პენალტი",
  SpoiledPenalty: "გაფუჭებული პენალტი",
  RepulsedPenalty: "მოგერიებული პენალტი",
  Blow: "დარტყმა",
  GoalOnDoor: "დარტყმა კარში",
};

export default Strings;
