export const SvgICONS = {
  Search: require('assets/svgs/search.svg').default,
  BrandLogo: require('assets/svgs/logo.svg').default,
  BrandLogoBlack: require('assets/svgs/blackLogo.svg').default,
  Menu: require('assets/svgs/menu.svg').default,
  Close: require('assets/svgs/close.svg').default,
  Edit: require('assets/svgs/edit.svg').default,
  CloseBlack: require('assets/svgs/closeBlack.svg').default,
  ArrowRight: require('assets/svgs/back.svg').default,
  Share: require('assets/svgs/share.svg').default,
  English: require('assets/svgs/english.svg').default,
  Hindi: require('assets/svgs/hindi.svg').default,
  Comment: require('assets/svgs/comment.svg').default,
  CommentWhite: require('assets/svgs/commentWhite.svg').default,
  ChevronDown: require('assets/svgs/chevronDown.svg').default,
  ChevronUp: require('assets/svgs/chevronUp.svg').default,
  Cricket: require('assets/svgs/cricket.svg').default,
  CricketWhite: require('assets/svgs/CricketWhite.svg').default,
  Football: require('assets/svgs/football.svg').default,
  Kabaddi: require('assets/svgs/kabaddi.svg').default,
  Tennis: require('assets/svgs/tennis.svg').default,
  Crown: require('assets/svgs/crown.svg').default,
  List: require('assets/svgs/list.svg').default,
  LisBlack: require('assets/svgs/listBlack.svg').default,
  Rectangle: require('assets/svgs/rectangle.svg').default,
  RectangleBlack: require('assets/svgs/rectangleBlack.svg').default,
  Logout: require('assets/svgs/logout.svg').default,
  Calendar: require('assets/svgs/Calendar.svg').default,
}

export type SvgICONSType = keyof typeof SvgICONS
